<a href="https://colab.research.google.com/github/Proteobacteria/Proteobacteria.github.io/blob/main/n121a_hypothesis_test_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src='https://i.imgur.com/RDAD11M.png' width = '200' align = 'right'>

## *DATA SCIENCE / SECTION 1 / SPRINT 2 / NOTE 1*

# 📝 Assignment

# 가설 검정

## 1. One-Sample T-test 연습



### 데이터 불러오기
- [서울시 가로수 데이터셋](https://data.seoul.go.kr/dataList/367/S/2/datasetView.do)을 사용합니다.

다음 링크를 참조하세요. 
<https://ds-lecture-data.s3.ap-northeast-2.amazonaws.com/seoul_tree/seoul_tree.txt>

In [4]:
import pandas as pd
import numpy as np
from scipy import stats

# colab의 출력을 소수점 이하 3자리로 제한
%precision 10
# pandas DataFrame의 소수점 출력을 3자릴 제한
pd.set_option('precision', 10)

In [5]:
tree = pd.read_csv('https://ds-lecture-data.s3.ap-northeast-2.amazonaws.com/seoul_tree/seoul_tree.txt', delimiter = "\t", skiprows=1)
tree

,기간,자치구,노선수,수량,은행나무,양버즘나무,느티나무,왕벚나무,은단풍나무,메타세콰이어,...,튜울립나무,칠엽수,포플러,느릅나무,살구나무,무궁화,소나무,목련,이팝나무,기타
0,2019,서울시,"1,412","307,351","108,050","62,474","37,473","34,150",545,"5,171",...,948,"1,533",7,504,234,"2,374","4,539",378,"20,088","20,112"
1,2019,종로구,70,"7,329","4,072","1,071",619,421,-,1,...,-,17,-,-,-,-,239,-,711,29
2,2019,중구,48,"8,250","3,640",162,460,289,-,-,...,7,-,-,-,21,46,"2,162",-,470,817
3,2019,용산구,39,"7,835","4,444","1,422",373,262,-,-,...,13,16,-,-,39,-,51,126,198,780
4,2019,성동구,38,"8,120","1,090","2,401","1,975",602,29,48,...,-,1,3,59,-,-,53,-,709,646
5,2019,광진구,28,"7,223","1,247","2,306","1,057",940,-,-,...,58,101,-,-,-,-,20,113,760,443
6,2019,동대문구,43,"10,664","3,749","3,342",855,747,-,60,...,37,19,-,1,26,1,-,-,"1,176",456
7,2019,중랑구,57,"8,365","2,774","2,759",471,354,-,74,...,-,-,-,-,-,212,64,-,449,"1,156"
8,2019,성북구,78,"8,449","2,722","1,282","1,014","1,656",66,65,...,4,-,-,-,9,5,97,-,853,547
9,2019,강북구,31,"7,789","3,510",934,324,497,284,-,...,5,-,-,140,-,-,"1,007",-,575,410
10,2019,도봉구,63,"9,572","4,914",323,779,"2,095",6,61,...,15,-,-,-,-,214,15,-,47,"1,070"
11,2019,노원구,50,"14,489","6,505","3,336","1,165","1,612",-,285,...,-,-,-,26,58,150,32,1,142,"1,135"
12,2019,은평구,35,"9,880","4,324","1,653",680,"1,748",-,16,...,-,9,-,-,-,3,-,-,443,582
13,2019,서대문구,39,"8,627","3,474","1,890",721,732,-,25,...,10,5,4,-,-,70,-,-,493,"1,120"
14,2019,마포구,92,"14,538","3,353","3,581","3,056","1,096",-,474,...,-,-,-,-,64,-,124,93,"1,280",348
15,2019,양천구,69,"13,501","5,622","3,992","1,065",956,-,74,...,-,4,-,-,-,197,-,-,784,595
16,2019,강서구,55,"13,719","3,977",706,"2,231","2,508",-,"1,651",...,-,110,-,-,-,59,282,-,"1,426",568
17,2019,구로구,81,"11,548","3,594","1,527","1,884","2,157",13,3,...,-,17,-,-,-,-,30,26,"1,082","1,210"
18,2019,금천구,30,"6,603","3,545","1,024",407,"1,123",-,35,...,-,7,-,-,-,-,5,-,184,69
19,2019,영등포구,114,"18,220","5,879","3,439","3,419","2,952",147,51,...,12,174,-,-,-,-,40,19,"1,281",651
20,2019,동작구,29,"7,083","2,178",829,"1,421","1,127",-,116,...,-,-,-,-,-,206,7,-,397,794
21,2019,관악구,32,"10,154","2,280","2,188",185,"2,416",-,95,...,-,-,-,-,-,"1,120",59,-,249,"1,194"
22,2019,서초구,56,"16,548","3,800","5,036","3,409",254,-,"1,159",...,-,721,-,-,-,91,-,-,446,"1,143"
23,2019,강남구,60,"23,349","7,210","7,559","2,991","2,455",-,864,...,65,-,-,-,-,-,-,-,768,913
24,2019,송파구,99,"22,858","11,894","4,180","2,400",992,-,14,...,722,329,-,-,-,-,215,-,"1,651",450
25,2019,강동구,66,"17,152","5,474","4,284","2,417","2,309",-,-,...,-,-,-,-,-,-,-,-,642,"1,969"
26,2019,공원녹지사업소,1,236,179,26,24,-,-,-,...,-,3,-,-,-,-,-,-,4,-
27,2019,시설관리공단,9,"15,250","2,600","1,222","2,071","1,850",-,-,...,-,-,-,278,17,-,37,-,"2,868","1,017"

### "서울시에는 구별로 평균 약 400 그루 정도의 `이팝나무`가 있다"라는 가설에 대해 가설검정을 시행하세요.

- 단, `서울시`, `공원녹지사업소`, `시설관리공단` 부분의 데이터는 제외합니다.
- 가설검정 결과의 pvalue 값을 `pv1`에 저장하세요. (`.pvalue` 사용)

In [6]:
tree_fringetree = pd.concat([tree['자치구'], tree['이팝나무']], axis=1)
drop_index = tree_fringetree[tree_fringetree['자치구'].isin(['서울시','공원녹지사업소','시설관리공단'])].index

tree1=tree_fringetree.drop(drop_index, axis=0)

tree1 = pd.to_numeric(tree1['이팝나무'].str.replace(',',''))

pv1 = stats.ttest_1samp(tree1, 400).pvalue
pv1

0.0024707129

### 이번에는 10개의 구를 샘플링하여, 위에 대한 가설검정을 다시 한번 시행해보세요.

- 단, 아래의 코드를 참조하여 sample을 위한 seed 는 123로 설정하세요.
- 가설검정 결과의 pvalue값을 `pv2`에 저장하세요

In [7]:
import numpy as np
np.random.seed(123)

random_index = np.random.choice(tree1.index, size = 10)  # "~"와 " "을 적절한 값으로 채우시면 됩니다
tree2=tree.iloc[random_index]

tree2 = pd.to_numeric(tree2['이팝나무'].str.replace(',',''))

pv2 = stats.ttest_1samp(tree2, 400).pvalue
pv2.round(5)

0.4977300000

## 2. Two-Sample T-test 연습

### "서울시의 구별 평균 느티나무수와 왕벚나무의 수는 차이가 없다"라는 가설에 대해 가설검정을 시행하세요.

- 단, `서울시`, `공원녹지사업소`, `시설관리공단` 부분의 데이터는 제외합니다.
- 가설검정 결과의 pvalue를 `pv3`에 저장하세요

In [8]:
trees = pd.concat([tree['자치구'], tree['느티나무'], tree['왕벚나무']], axis=1)
trees = trees.drop(drop_index, axis=0)

tree_zelkova = pd.concat([trees['자치구'], trees['느티나무']], axis=1)
tree_cherry = pd.concat([trees['자치구'], trees['왕벚나무']], axis=1)

tree_zelkova = pd.to_numeric(tree_zelkova['느티나무'].str.replace(',',''))
tree_cherry = pd.to_numeric(tree_cherry['왕벚나무'].str.replace(',',''))

pv3 = stats.ttest_ind(tree_zelkova, tree_cherry).pvalue
pv3

0.6455096880


### Two-Sample One-tailed test를 사용하여 **평균 느티나무수가 왕벚나무 수보다 크다**라는 가설에 대한 가설검정을 시행하세요.
- 해당 가설검정의 결과를 `ans`에 저장하세요.

이 때 `ans`가 가질 수 있는 값은 아래와 같습니다 :
1. "느티나무" ( 느티나무의 수가 통계적으로 유의하게 많은 경우 )
2. "왕벚나무" ( 왕벚나무의 수가 통계적으로 유의하게 많은 경우 )
3. "없음" (통계적으로 유의하지 않은 경우)

Two-Sample One-tailed test를 scipy에서 하는 방법은 아래의 링크를 참고 하세요  
참고 링크 : https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html

In [1]:
# 아래의 코드를 실행해주세요
!pip install scipy --upgrade

Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (1.7.3)
Requirement already satisfied: numpy<1.23.0,>=1.16.5 in /usr/local/lib/python3.7/dist-packages (from scipy) (1.21.5)

# 가설의 대한 가설검정 ➡ p-value


*  ```p-value < 0.05``` ➡ **귀무가설 옳을 확률 5% 미만** - *대립가설 채택*

>  ⬛ ```p-value < 0.01``` ➡ **귀무가설이 옳을 확률 1% 미만** ➡ 깐깐한 기준

*  ```0.05 ≤ p-value ≤ 0.1``` ➡ 애매함

*  ```p-value > 0.1``` ➡ 귀무가설 채택

In [10]:
from scipy import stats

result1 = stats.ttest_ind(tree_zelkova, tree_cherry, alternative='greater').pvalue

result2 = stats.ttest_ind(tree_zelkova, tree_cherry, alternative='less').pvalue

if result1 < 0.05:
  ans = '느티나무'
if result2 < 0.05:
  ans = '왕벚나무'
else:
  ans = '없음'


ans

'없음'

## 🔥 **도전과제**
> 2문제 모두 하면 됩니다.

### 1. Compare mean for multiple-sample 
 
다음 링크를 참조하세요. <https://reneshbedre.github.io/blog/anova.html>

구별, 은행나무, 양버즘나무, 느티나무에 대해서 ANOVA Test를 실행하세요.

단, `서울시`, `공원녹지사업소`, `시설관리공단` 부분의 데이터는 제외합니다.

In [ ]:
# 이 곳에 답안을 작성하시기 바랍니다

### 2. Sampling

- 세션 시간에 배웠던 4가지 sampling (Simple Random, Systematic, Stratified Random, Cluster) 방식을 구현해보세요.

- 이를 위한 데이터는 1 부터 100을 담은 numpy array이며, Sampling 해야 하는 수는 20개 입니다.

- Stratified Random Sampling을 위한 그룹을 나누는 기준은 1-10, 11-20, ... 과 같은 방식입니다.

- Cluster Sampling에서 그룹을 나누는 기준은 5로 나눴을때의 나머지 값입니다. (0,1,2,3,4)

In [ ]:
# 이 곳에 답안을 작성하시기 바랍니다